[2023-12-16T18:44:33.343+0000] {processor.py:157} INFO - Started process (PID=33379) to work on /Workspace/Repos/avezumgabriel@gmail.com/brewery_dl/airflow/dags/my_dag.py
[2023-12-16T18:44:33.344+0000] {processor.py:829} INFO - Processing file /Workspace/Repos/avezumgabriel@gmail.com/brewery_dl/airflow/dags/my_dag.py for tasks to queue
[2023-12-16T18:44:33.346+0000] {logging_mixin.py:154} INFO - [2023-12-16T18:44:33.345+0000] {dagbag.py:536} INFO - Filling up the DagBag from /Workspace/Repos/avezumgabriel@gmail.com/brewery_dl/airflow/dags/my_dag.py
[2023-12-16T18:44:33.669+0000] {logging_mixin.py:154} INFO - [2023-12-16T18:44:33.599+0000] {dagbag.py:346} ERROR - Failed to import: /Workspace/Repos/avezumgabriel@gmail.com/brewery_dl/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-1d2ad686-a70d-44ab-98a8-785814703250/lib/python3.10/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Workspace/Repos/avezumgabriel@gmail.com/brewery_dl/airflow/dags/my_dag.py", line 5, in <module>
    from read_raw_data import read_raw_df
ModuleNotFoundError: No module named 'read_raw_data'
[2023-12-16T18:44:33.760+0000] {processor.py:841} WARNING - No viable dags retrieved from /Workspace/Repos/avezumgabriel@gmail.com/brewery_dl/airflow/dags/my_dag.py
[2023-12-16T18:44:34.331+0000] {processor.py:179} INFO - Processing /Workspace/Repos/avezumgabriel@gmail.com/brewery_dl/airflow/dags/my_dag.py took 0.992 seconds
